### PR TITLE
Arubinu42 Based Theme added as Version 3

### PR DESCRIPTION
**Pull request by marioesho**
- Moved BakkesMod Debug path to user vcxproj file
- Added similar theme from [OverLay4RocketStats/themes/Arubinu42](https://github.com/Arubinu/Overlay4RocketStats/tree/master/themes/Arubinu42)
- Used streak image from [OverLay4RocketStats/assets](https://github.com/Arubinu/Overlay4RocketStats/tree/master/assets)
- Updated Readme with current versions

### CODE REVIEW

**Comment by Lyliya** [comment]
Hi @marioesho 
Thanks for your time spent on RocketStats and your PR :)
Adding Third-Party theme as an in game theme is not something we usually allow, but after speaking with Arubinu, it seems ok for him

I have one concern about your implementation. When we remove one of the displayed stat, the background image does not shrink to fit the text size, leading to useless space left
image

Also, your condition for what overlay to display is kinda misleading (RocketStats.cpp L537, L590). Can you use if(v1) else if (v2) else v3 ?

**Comment by marioesho** [comment]
Great! I forgot stats can be removed. I will work on that when I am free and let you know when it is ready for review. For the condition, I thought you would want the original as the else statement. I can make that change as well.

Thanks,
Mario Esho
________________________________

**Comment by marioesho** [comment]
Hello @Lyliya,

I have made the changes requested. I couldn't use the background image because there isn't a way to resize the image on the x axis, so I used a `FillBox` instead. Let me know if there is any issues with the code. I know this can be refactored to create the `FillBox` better so let me know.

**Comment by Lyliya** [comment]
Yep, i have seen it, i'll review it when i have the time, probable next week, thanks ;)

**Comment by marioesho** [comment]
@Lyliya just a reminder about reviewing this PR whenever you have a chance. Thanks!

**Pull request merged**
